wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.6425011169935017
input_chunk_length:
  value: 60
kernel_size:
  value: 5
lr:
  value: 0.20849061036333133
n_epochs:
  value: 100
num_filters:
  value: 16
num_layers:
  value: 16
num_outputs:
  value: 0
weight_norm:
  value: false
