wandb_version: 1

batch_size:
  value: 128
dropout:
  value: 0.8804026733017019
input_chunk_length:
  value: 40
kernel_size:
  value: 3
lr:
  value: 0.0997577544754428
n_epochs:
  value: 400
num_filters:
  value: 8
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: false
