wandb_version: 1

batch_size:
  value: 64
dropout:
  value: 0.3851529303292027
input_chunk_length:
  value: 80
kernel_size:
  value: 3
lr:
  value: 0.04035528436845372
n_epochs:
  value: 400
num_filters:
  value: 64
num_layers:
  value: 8
num_outputs:
  value: 0
weight_norm:
  value: false
