wandb_version: 1

batch_size:
  value: 32
dropout:
  value: 0.8913276876693278
input_chunk_length:
  value: 80
kernel_size:
  value: 5
lr:
  value: 0.06703912649238106
n_epochs:
  value: 400
num_filters:
  value: 16
num_layers:
  value: 4
num_outputs:
  value: 0
weight_norm:
  value: true
