name: pyprocessta
channels:
  - defaults
  - conda-forge
dependencies:
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.7.4.post0=py38hea4295b_0
  - anyio=2.2.0=py38hca03da5_2
  - appnope=0.1.2=py38hca03da5_1001
  - argon2-cffi=20.1.0=py38h1a28f6b_2
  - async-timeout=3.0.1=py_1000
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.0.0=pyhd3eb1b0_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py38h1a28f6b_1002
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2021.10.8=h4653dfc_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2021.10.8=py38h10201cd_0
  - cffi=1.14.5=py38h9e348fd_0
  - chardet=4.0.0=py38h10201cd_1
  - click=8.0.3=py38h10201cd_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - convertdate=2.3.2=pyhd8ed1ab_0
  - cryptography=36.0.0=py38h834c97f_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py38hc377ac9_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38hca03da5_0
  - filterpy=1.4.5=py_1
  - freetype=2.10.4=h17b34a0_1
  - future=0.18.2=py38h10201cd_3
  - google-auth=2.3.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - hijri-converter=2.2.2=pyhd8ed1ab_0
  - holidays=0.12=pyhd8ed1ab_0
  - idna=3.3=pyhd3eb1b0_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - ipykernel=6.4.1=py38hca03da5_1
  - ipython=7.29.0=py38h86d0a89_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jbig=2.1=h3422bc3_2003
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38hca03da5_0
  - jupyter_server=1.4.1=py38hca03da5_0
  - jupyterlab=3.2.1=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.2=pyhd3eb1b0_0
  - kiwisolver=1.3.2=py38h1670459_0
  - korean_lunar_calendar=0.2.1=pyh9f0ad1d_0
  - lcms2=2.12=had6a04f_0
  - lerc=2.2.1=h9f76cd9_0
  - libblas=3.9.0=12_osxarm64_openblas
  - libcblas=3.9.0=12_osxarm64_openblas
  - libcxx=12.0.0=hf6beb65_1
  - libdeflate=1.7=h27ca646_5
  - libffi=3.4.2=hc377ac9_2
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=12_osxarm64_openblas
  - libopenblas=0.3.18=openmp_h5dd58f0_0
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.16.0=hccf11d3_0
  - libsodium=1.0.18=h1a28f6b_0
  - libtiff=4.3.0=hc6122e1_1
  - libwebp-base=1.2.1=h3422bc3_0
  - llvm-openmp=12.0.1=hf3c4609_1
  - lz4-c=1.9.3=hbdafb3b_1
  - markdown=3.3.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py38h1a28f6b_0
  - matplotlib-base=3.4.3=py38hb140015_1
  - mistune=0.8.4=py38h1a28f6b_1000
  - multidict=5.2.0=py38hea4295b_0
  - nb_conda=2.2.1=py38hca03da5_1
  - nb_conda_kernels=2.3.1=py38hca03da5_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.3.0=py38hca03da5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h1a28f6b_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - ninja=1.10.2=hc021e02_1
  - notebook=6.4.6=py38hca03da5_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1l=h3422bc3_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38hca03da5_1
  - parso=0.8.3=pyhd3eb1b0_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.2.4=py38hca03da5_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyasn1=0.4.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyjwt=2.3.0=pyhd8ed1ab_1
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyrsistent=0.18.0=py38h1a28f6b_0
  - pysocks=1.7.1=py38hca03da5_0
  - python=3.8.11=hbdb9e5c_5
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.9.0=cpu_py38hff7f1bc_2
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyzmq=22.3.0=py38hc377ac9_2
  - readline=8.1=h1a28f6b_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.8=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38hca03da5_1
  - six=1.16.0=pyhd3eb1b0_0
  - sleef=3.5.1=h156473d_2
  - sniffio=1.2.0=py38hca03da5_1
  - sqlite=3.37.0=h1058600_0
  - tensorboard=2.7.0=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - terminado=0.9.4=py38hca03da5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=hb8d0fd4_0
  - tornado=6.1=py38h1a28f6b_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing-extensions=4.0.1=hd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - u8darts=0.15.0=pyhd8ed1ab_0
  - u8darts-torch=0.15.0=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38hca03da5_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - xarray=0.20.2=pyhd8ed1ab_0
  - xz=5.2.5=h1a28f6b_0
  - yarl=1.7.0=py38hea4295b_0
  - zeromq=4.3.4=hc377ac9_0
  - zlib=1.2.11=h5a0b063_4
  - zstd=1.5.0=h861e0a7_0
  - pip:
    - black==21.12b0
    - charset-normalizer==2.0.10
    - configparser==5.2.0
    - cython==0.29.26
    - docker-pycreds==0.4.0
    - ephem==4.1.3
    - et-xmlfile==1.1.0
    - fonttools==4.28.5
    - gitdb==4.0.9
    - gitpython==3.1.26
    - grpcio==1.43.0
    - importlib-metadata==4.10.0
    - jedi==0.18.1
    - lightgbm==3.3.1
    - lunarcalendar==0.0.9
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mypy-extensions==0.4.3
    - numpy==1.22.0
    - openpyxl==3.0.9
    - pandas==1.3.5
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pillow==9.0.0
    - platformdirs==2.4.1
    - plotly==5.5.0
    - plotly-express==0.4.1
    - promise==2.3
    - prompt-toolkit==3.0.24
    - protobuf==3.19.1
    - psutil==5.9.0
    - pyasn1-modules==0.2.8
    - pygments==2.11.2
    - pymeeus==0.5.11
    - pyparsing==3.0.6
    - pystan==2.19.1.1
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.27.1
    - scienceplots==1.0.9
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.11.2
    - sentry-sdk==1.5.2
    - setuptools-git==1.2
    - shortuuid==1.0.8
    - smmap==5.0.0
    - statsmodels==0.13.1
    - subprocess32==3.5.4
    - tenacity==8.0.1
    - tensorboard-data-server==0.6.1
    - termcolor==1.1.0
    - tomli==1.2.3
    - torch==1.10.1
    - ujson==5.1.0
    - urllib3==1.26.7
    - wandb==0.12.9
    - werkzeug==2.0.2
    - yaspin==2.1.0
    - zipp==3.7.0
